// SPDX-License-Identifier: MIT

use std::{
    collections::{BTreeMap, BTreeSet},
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use quote::ToTokens;
use roxmltree::{Document, Node};
use syn::{Attribute, ImplItem, Item, Visibility};

const GENERATED_NOTICE: &str = "<!-- Generated by table-docs-api. Do not edit manually. -->\n\n";

#[derive(Clone, Debug)]
struct ApiEntry {
    name: String,
    signature: String,
    docs: String,
}

fn main() -> Result<(), String> {
    let check = env::args().skip(1).any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let pages = generate_pages(&root)?;
    let output = root.join("docs/reference");
    if check {
        check_pages(&output, &pages)
    } else {
        write_pages(&output, &pages)
    }
}

fn generate_pages(root: &Path) -> Result<BTreeMap<String, String>, String> {
    let xml_root = root.join("build/docs/api/xml");
    let c_file = read_xml(&xml_root.join("table_8h.xml"))?;
    let cpp_curve = read_xml(&xml_root.join("classtable_1_1Curve.xml"))?;
    let cpp_map = read_xml(&xml_root.join("classtable_1_1Map.xml"))?;
    let cpp_namespace = read_xml(&xml_root.join("namespacetable.xml"))?;

    let c_functions = xml_entries(&c_file, "function");
    let mut pages = BTreeMap::new();
    pages.insert("c/index.md".into(), c_index());
    pages.insert("c/types.md".into(), render_c_types(&xml_root, &c_file)?);
    pages.insert(
        "c/initialisation.md".into(),
        render_entries(
            "C initialisation and validation",
            "Create validated borrowed views or mutable bindings before lookup.",
            "c",
            c_functions
                .iter()
                .filter(|entry| entry.name.ends_with("_init") || entry.name == "table_validate"),
        ),
    );
    pages.insert(
        "c/lookup.md".into(),
        render_entries(
            "C lookup and access",
            "Lookups clamp finite coordinates; accessors preserve the stored scalar type.",
            "c",
            c_functions
                .iter()
                .filter(|entry| entry.name.contains("lookup") || entry.name.contains("_get_")),
        ),
    );
    pages.insert(
        "c/mutation.md".into(),
        render_entries(
            "C mutation and replacement",
            "Mutations validate ordering and types. Whole-table replacement validates before copying.",
            "c",
            c_functions.iter().filter(|entry| {
                entry.name.contains("_set_") || entry.name == "table_replace"
            }),
        ),
    );

    pages.insert("cpp/index.md".into(), cpp_index());
    pages.insert(
        "cpp/status.md".into(),
        render_named_xml_entry("C++ Status", "cpp", &cpp_namespace, "enum", "Status")?,
    );
    pages.insert(
        "cpp/curve.md".into(),
        render_cpp_class("C++ Curve", &cpp_curve),
    );
    pages.insert("cpp/map.md".into(), render_cpp_class("C++ Map", &cpp_map));

    let rust = RustApi::load(root)?;
    pages.insert("rust/index.md".into(), rust_index());
    pages.insert(
        "rust/curve.md".into(),
        rust.render_type_page("Rust Curve", "Curve")?,
    );
    pages.insert(
        "rust/map.md".into(),
        rust.render_type_page("Rust Map", "Map")?,
    );
    pages.insert("rust/types.md".into(), rust.render_types_page()?);
    pages.insert("rust/protobuf.md".into(), rust.render_protobuf_page()?);
    pages.insert("rust/table-sys.md".into(), table_sys_page());
    Ok(pages)
}

fn read_xml(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("failed to read {}: {error}", path.display()))
}

fn xml_entries(xml: &str, kind: &str) -> Vec<ApiEntry> {
    let document = Document::parse(xml).expect("Doxygen emitted valid XML");
    document
        .descendants()
        .filter(|node| {
            node.has_tag_name("memberdef")
                && node.attribute("kind") == Some(kind)
                && node.attribute("prot") == Some("public")
        })
        .filter_map(xml_entry)
        .collect()
}

fn xml_entry(node: Node<'_, '_>) -> Option<ApiEntry> {
    let name = child_text(node, "name");
    if name.is_empty() {
        return None;
    }
    let definition = child_text(node, "definition");
    let args = child_text(node, "argsstring");
    let signature = if node.attribute("kind") == Some("enum") {
        if node.attribute("strong") == Some("yes") {
            let qualified = child_text(node, "qualifiedname");
            format!("enum class {qualified}")
        } else {
            format!("typedef enum {name} {name}_t")
        }
    } else if definition.is_empty() {
        name.clone()
    } else {
        format!("{definition}{args}")
    };
    let brief = child(node, "briefdescription").map_or_else(String::new, node_text);
    let detail = child(node, "detaileddescription").map_or_else(String::new, node_text);
    let mut docs = match (brief.is_empty(), detail.is_empty()) {
        (false, false) => format!("{brief}\n\n{detail}"),
        (false, true) => brief,
        (true, false) => detail,
        (true, true) => String::new(),
    };
    let variants = node
        .children()
        .filter(|child| child.has_tag_name("enumvalue"))
        .map(|variant| child_text(variant, "name"))
        .filter(|name| !name.is_empty())
        .map(|name| format!("`{name}`"))
        .collect::<Vec<_>>();
    if !variants.is_empty() {
        if !docs.is_empty() {
            docs.push_str("\n\n");
        }
        write!(docs, "Values: {}.", variants.join(", ")).expect("writing to a String cannot fail");
    }
    Some(ApiEntry {
        name,
        signature: clean_space(&signature),
        docs,
    })
}

fn child<'a>(node: Node<'a, 'a>, name: &str) -> Option<Node<'a, 'a>> {
    node.children().find(|child| child.has_tag_name(name))
}

fn child_text(node: Node<'_, '_>, name: &str) -> String {
    child(node, name).map_or_else(String::new, node_text)
}

fn node_text(node: Node<'_, '_>) -> String {
    clean_space(
        &node
            .descendants()
            .filter(roxmltree::Node::is_text)
            .filter_map(|descendant| descendant.text())
            .collect::<Vec<_>>()
            .join(""),
    )
}

fn clean_space(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn render_entries<'a>(
    title: &str,
    introduction: &str,
    language: &str,
    entries: impl Iterator<Item = &'a ApiEntry>,
) -> String {
    let mut output = format!("{GENERATED_NOTICE}# {title}\n\n{introduction}\n\n");
    for entry in entries {
        write!(
            output,
            "## `{}`\n\n```{language}\n{};\n```\n\n{}\n\n",
            entry.name, entry.signature, entry.docs
        )
        .expect("writing to a String cannot fail");
    }
    output
}

fn render_c_types(xml_root: &Path, file_xml: &str) -> Result<String, String> {
    let document = Document::parse(file_xml).map_err(|error| error.to_string())?;
    let mut entries = xml_entries(file_xml, "enum");
    for inner in document
        .descendants()
        .filter(|node| node.has_tag_name("innerclass"))
    {
        let Some(reference) = inner.attribute("refid") else {
            continue;
        };
        let struct_xml = read_xml(&xml_root.join(format!("{reference}.xml")))?;
        let struct_document = Document::parse(&struct_xml).map_err(|error| error.to_string())?;
        let compound = struct_document
            .descendants()
            .find(|node| node.has_tag_name("compounddef"))
            .ok_or_else(|| format!("missing compound definition for {reference}"))?;
        let name = child_text(compound, "compoundname");
        let mut docs = child(compound, "briefdescription").map_or_else(String::new, node_text);
        let fields = xml_entries(&struct_xml, "variable")
            .into_iter()
            .map(|field| format!("`{}`", field.name))
            .collect::<Vec<_>>();
        if !fields.is_empty() {
            write!(docs, "\n\nFields: {}.", fields.join(", "))
                .expect("writing to a String cannot fail");
        }
        entries.push(ApiEntry {
            signature: format!("typedef struct {name} {name}_t"),
            name,
            docs,
        });
    }
    Ok(render_entries(
        "C types and status",
        "The C API uses explicit descriptors and scalar tags over caller-owned storage.",
        "c",
        entries.iter(),
    ))
}

fn render_named_xml_entry(
    title: &str,
    language: &str,
    xml: &str,
    kind: &str,
    name: &str,
) -> Result<String, String> {
    let entries = xml_entries(xml, kind);
    let entry = entries
        .iter()
        .find(|entry| entry.name == name)
        .ok_or_else(|| {
            let available = entries
                .iter()
                .map(|entry| entry.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            format!("Doxygen XML does not contain {name}; found: {available}")
        })?;
    Ok(render_entries(title, "", language, std::iter::once(entry)))
}

fn render_cpp_class(title: &str, xml: &str) -> String {
    let document = Document::parse(xml).expect("Doxygen emitted valid XML");
    let compound = document
        .descendants()
        .find(|node| node.has_tag_name("compounddef"))
        .expect("class XML contains a compound");
    let name = child_text(compound, "compoundname");
    let docs = child(compound, "briefdescription").map_or_else(String::new, node_text);
    let template = child(compound, "templateparamlist").map_or_else(String::new, |parameters| {
        parameters
            .children()
            .filter(|node| node.has_tag_name("param"))
            .map(|parameter| {
                let kind = child_text(parameter, "type");
                let name = child_text(parameter, "declname");
                let default = child_text(parameter, "defval");
                let mut value = if name.is_empty() {
                    kind
                } else {
                    format!("{kind} {name}")
                };
                if !default.is_empty() {
                    write!(value, " = {default}").expect("writing to a String cannot fail");
                }
                value
            })
            .collect::<Vec<_>>()
            .join(", ")
    });
    let methods = xml_entries(xml, "function");
    let mut output = format!(
        "{GENERATED_NOTICE}# {title}\n\n```cpp\ntemplate <{template}>\nclass {name}\n```\n\n{docs}\n\n"
    );
    for method in methods.iter().filter(|method| !method.docs.is_empty()) {
        write!(
            output,
            "## `{}`\n\n```cpp\n{}\n```\n\n{}\n\n",
            method.name, method.signature, method.docs
        )
        .expect("writing to a String cannot fail");
    }
    output
}

fn c_index() -> String {
    format!(
        "{GENERATED_NOTICE}# C API\n\nThe C11 API binds validated caller-owned arrays and never allocates heap memory.\n\n- [Types and status](./types)\n- [Initialisation and validation](./initialisation)\n- [Lookup and access](./lookup)\n- [Mutation and replacement](./mutation)\n"
    )
}

fn cpp_index() -> String {
    format!(
        "{GENERATED_NOTICE}# C++ API\n\nThe C++11 facade owns fixed-size arrays and delegates validation and interpolation to the C core.\n\n- [`Status`](./status)\n- [`Curve`](./curve)\n- [`Map`](./map)\n"
    )
}

fn rust_index() -> String {
    format!(
        "{GENERATED_NOTICE}# Rust API\n\nThe safe `table` crate owns dynamically sized arrays while reusing the C implementation.\n\n- [`Curve`](./curve)\n- [`Map`](./map)\n- [Errors and scalar types](./types)\n- [Protobuf snapshots](./protobuf)\n- [Low-level `table-sys`](./table-sys)\n"
    )
}

fn table_sys_page() -> String {
    format!(
        "{GENERATED_NOTICE}# Low-level `table-sys`\n\n`table-sys` exposes the raw C ABI for language-integration work. Ordinary Rust applications should use the safe `table` crate. Its functions and structures correspond directly to the [C API](../c/).\n"
    )
}

#[derive(Default)]
struct RustApi {
    items: BTreeMap<String, RustItem>,
    methods: BTreeMap<String, Vec<ApiEntry>>,
}

#[derive(Clone, Default)]
struct RustItem {
    name: String,
    signature: String,
    docs: String,
    variants: Vec<ApiEntry>,
}

impl RustApi {
    fn load(root: &Path) -> Result<Self, String> {
        let mut api = Self::default();
        for relative in [
            "rust/table/src/lib.rs",
            "rust/table/src/scalar.rs",
            "rust/table/src/proto.rs",
        ] {
            let path = root.join(relative);
            let source = fs::read_to_string(&path)
                .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
            let syntax = syn::parse_file(&source)
                .map_err(|error| format!("failed to parse {}: {error}", path.display()))?;
            api.collect(&syntax.items);
        }
        let generated_path = root.join("rust/table/src/generated/table.v1.rs");
        let generated_source = fs::read_to_string(&generated_path)
            .map_err(|error| format!("failed to read {}: {error}", generated_path.display()))?;
        let generated_syntax = syn::parse_file(&generated_source)
            .map_err(|error| format!("failed to parse {}: {error}", generated_path.display()))?;
        let mut messages = Self::default();
        messages.collect(&generated_syntax.items);
        let scalar_array = messages
            .items
            .remove("ScalarArray")
            .ok_or_else(|| "generated Prost API does not contain ScalarArray".to_owned())?;
        api.items.insert("MessageScalarArray".into(), scalar_array);
        Ok(api)
    }

    fn collect(&mut self, items: &[Item]) {
        for item in items {
            match item {
                Item::Struct(value) if is_public(&value.vis) && !doc_hidden(&value.attrs) => {
                    let name = value.ident.to_string();
                    self.items.insert(
                        name.clone(),
                        RustItem {
                            name,
                            signature: clean_tokens(&format!(
                                "pub struct {}{}",
                                value.ident,
                                value.generics.to_token_stream()
                            )),
                            docs: rust_docs(&value.attrs),
                            variants: Vec::new(),
                        },
                    );
                }
                Item::Enum(value) if is_public(&value.vis) && !doc_hidden(&value.attrs) => {
                    let name = value.ident.to_string();
                    let variants = value
                        .variants
                        .iter()
                        .map(|variant| ApiEntry {
                            name: variant.ident.to_string(),
                            signature: variant.to_token_stream().to_string(),
                            docs: rust_docs(&variant.attrs),
                        })
                        .collect();
                    self.items.insert(
                        name.clone(),
                        RustItem {
                            name: name.clone(),
                            signature: format!("pub enum {name}"),
                            docs: rust_docs(&value.attrs),
                            variants,
                        },
                    );
                }
                Item::Trait(value) if is_public(&value.vis) && !doc_hidden(&value.attrs) => {
                    let name = value.ident.to_string();
                    self.items.insert(
                        name.clone(),
                        RustItem {
                            name,
                            signature: clean_tokens(&format!(
                                "pub trait {}{}: {}",
                                value.ident,
                                value.generics.to_token_stream(),
                                value.supertraits.to_token_stream()
                            )),
                            docs: rust_docs(&value.attrs),
                            variants: Vec::new(),
                        },
                    );
                }
                Item::Impl(value) => {
                    let Some(name) = type_name(&value.self_ty) else {
                        continue;
                    };
                    for member in &value.items {
                        if let ImplItem::Fn(function) = member
                            && is_public(&function.vis)
                            && !doc_hidden(&function.attrs)
                        {
                            self.methods
                                .entry(name.clone())
                                .or_default()
                                .push(ApiEntry {
                                    name: function.sig.ident.to_string(),
                                    signature: clean_tokens(&format!(
                                        "pub {}",
                                        function.sig.to_token_stream()
                                    )),
                                    docs: rust_docs(&function.attrs),
                                });
                        }
                    }
                }
                Item::Mod(module) if is_public(&module.vis) => {
                    if let Some((_, nested)) = &module.content {
                        self.collect(nested);
                    }
                }
                _ => {}
            }
        }
    }

    fn render_type_page(&self, title: &str, name: &str) -> Result<String, String> {
        let item = self
            .items
            .get(name)
            .ok_or_else(|| format!("Rust API does not contain {name}"))?;
        let mut output = format!(
            "{GENERATED_NOTICE}# {title}\n\n```rust\n{}\n```\n\n{}\n\n",
            item.signature, item.docs
        );
        for method in self.methods.get(name).into_iter().flatten() {
            write!(
                output,
                "## `{}`\n\n```rust\n{}\n```\n\n{}\n\n",
                method.name, method.signature, method.docs
            )
            .expect("writing to a String cannot fail");
        }
        Ok(output)
    }

    fn render_types_page(&self) -> Result<String, String> {
        let mut output = format!(
            "{GENERATED_NOTICE}# Rust errors and scalar types\n\nThe safe crate exposes explicit error and scalar representations.\n\n"
        );
        for name in ["Error", "Scalar", "ScalarType"] {
            output.push_str(&self.render_item(name)?);
        }
        Ok(output)
    }

    fn render_protobuf_page(&self) -> Result<String, String> {
        let mut output = format!(
            "{GENERATED_NOTICE}# Rust Protobuf snapshots\n\nEnable the `prost` feature to use stable `table.v1` messages and validated conversions. `Curve` and `Map` implement conversions to and from their corresponding messages.\n\n"
        );
        for name in ["SnapshotError", "MessageScalarArray"] {
            output.push_str(&self.render_item(name)?);
        }
        output.push_str("## Messages\n\nThe generated `table::proto::v1` module contains `ScalarArray`, `Curve`, `Map`, and `ScalarType`.\n");
        Ok(output)
    }

    fn render_item(&self, name: &str) -> Result<String, String> {
        let item = self
            .items
            .get(name)
            .ok_or_else(|| format!("Rust API does not contain {name}"))?;
        let mut output = format!(
            "## `{}`\n\n```rust\n{}\n```\n\n{}\n\n",
            item.name, item.signature, item.docs
        );
        if !item.variants.is_empty() {
            output.push_str("| Variant | Meaning |\n| --- | --- |\n");
            for variant in &item.variants {
                writeln!(output, "| `{}` | {} |", variant.name, variant.docs)
                    .expect("writing to a String cannot fail");
            }
            output.push('\n');
        }
        Ok(output)
    }
}

fn is_public(visibility: &Visibility) -> bool {
    matches!(visibility, Visibility::Public(_))
}

fn doc_hidden(attributes: &[Attribute]) -> bool {
    attributes.iter().any(|attribute| {
        attribute.path().is_ident("doc")
            && attribute
                .meta
                .to_token_stream()
                .to_string()
                .contains("hidden")
    })
}

fn rust_docs(attributes: &[Attribute]) -> String {
    let mut lines = Vec::new();
    for attribute in attributes {
        if !attribute.path().is_ident("doc") {
            continue;
        }
        if let syn::Meta::NameValue(value) = &attribute.meta
            && let syn::Expr::Lit(expression) = &value.value
            && let syn::Lit::Str(text) = &expression.lit
        {
            lines.push(text.value().trim().to_owned());
        }
    }
    lines.join("\n").replace("[`", "`").replace("`]", "`")
}

fn type_name(value: &syn::Type) -> Option<String> {
    if let syn::Type::Path(path) = value {
        path.path
            .segments
            .last()
            .map(|segment| segment.ident.to_string())
    } else {
        None
    }
}

fn clean_tokens(value: &str) -> String {
    value
        .replace(" < ", "<")
        .replace("< ", "<")
        .replace(" >", ">")
        .replace(" :: ", "::")
        .replace(" ,", ",")
        .replace(" : ", ": ")
        .replace(" (& ", "(&")
        .replace(" (& mut ", "(&mut ")
        .replace("& mut ", "&mut ")
        .replace("& self", "&self")
        .replace("& [", "&[")
        .replace(" (", "(")
        .replace("[ ", "[")
        .replace(" ]", "]")
}

fn expected_files(pages: &BTreeMap<String, String>) -> BTreeSet<PathBuf> {
    pages.keys().map(PathBuf::from).collect()
}

fn check_pages(output: &Path, pages: &BTreeMap<String, String>) -> Result<(), String> {
    for (relative, expected) in pages {
        let path = output.join(relative);
        let actual = fs::read_to_string(&path)
            .map_err(|_| format!("{} is missing; run task docs:api", path.display()))?;
        if &actual != expected {
            return Err(format!("{} is stale; run task docs:api", path.display()));
        }
    }
    let expected = expected_files(pages);
    let mut existing = BTreeSet::new();
    collect_markdown(output, output, &mut existing)?;
    if existing != expected {
        return Err("generated API file set is stale; run task docs:api".into());
    }
    Ok(())
}

fn write_pages(output: &Path, pages: &BTreeMap<String, String>) -> Result<(), String> {
    if output.exists() {
        fs::remove_dir_all(output)
            .map_err(|error| format!("failed to clear {}: {error}", output.display()))?;
    }
    for (relative, content) in pages {
        let path = output.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&path, content)
            .map_err(|error| format!("failed to write {}: {error}", path.display()))?;
    }
    println!("Generated {} API reference pages", pages.len());
    Ok(())
}

fn collect_markdown(
    root: &Path,
    current: &Path,
    files: &mut BTreeSet<PathBuf>,
) -> Result<(), String> {
    if !current.exists() {
        return Ok(());
    }
    for entry in fs::read_dir(current).map_err(|error| error.to_string())? {
        let path = entry.map_err(|error| error.to_string())?.path();
        if path.is_dir() {
            collect_markdown(root, &path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "md") {
            files.insert(
                path.strip_prefix(root)
                    .map_err(|error| error.to_string())?
                    .to_owned(),
            );
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{RustApi, clean_space, node_text, rust_docs, xml_entries};

    #[test]
    fn normalises_generated_whitespace() {
        assert_eq!(clean_space("  one\n two   three "), "one two three");
    }

    #[test]
    fn extracts_rust_doc_attributes() {
        let item: syn::ItemStruct = syn::parse_quote! {
            /// First line.
            /// Second line.
            pub struct Example;
        };
        assert_eq!(rust_docs(&item.attrs), "First line.\nSecond line.");
    }

    #[test]
    fn extracts_doxygen_signatures_docs_and_enum_values() {
        let xml = r#"<doxygen><memberdef kind="enum" prot="public" strong="no">
          <name>state</name><enumvalue><name>STATE_OK</name></enumvalue>
          <briefdescription><para>Operation state.</para></briefdescription>
        </memberdef></doxygen>"#;
        let entries = xml_entries(xml, "enum");
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].signature, "typedef enum state state_t");
        assert!(entries[0].docs.contains("`STATE_OK`"));
    }

    #[test]
    fn preserves_inline_doxygen_text_boundaries() {
        let xml = r#"<para>Cells indexed as <computeroutput>[<ref>y</ref>][<ref>x</ref>]</computeroutput>. </para>"#;
        let document = roxmltree::Document::parse(xml).expect("test XML is valid");
        assert_eq!(
            node_text(document.root_element()),
            "Cells indexed as [y][x]."
        );
    }

    #[test]
    fn extracts_public_rust_generics_and_methods() {
        let syntax: syn::File = syn::parse_quote! {
            /// An owner.
            pub struct Owner<T> { value: T }
            impl<T> Owner<T> {
                /// Creates an owner.
                pub fn new(value: T) -> Self { Self { value } }
            }
        };
        let mut api = RustApi::default();
        api.collect(&syntax.items);
        assert_eq!(api.items["Owner"].signature, "pub struct Owner<T>");
        assert_eq!(api.methods["Owner"][0].name, "new");
        assert_eq!(api.methods["Owner"][0].docs, "Creates an owner.");
    }
}
