/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "table/v1/table.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(table_v1_ScalarArray, table_v1_ScalarArray, AUTO)


PB_BIND(table_v1_Curve, table_v1_Curve, AUTO)


PB_BIND(table_v1_Map, table_v1_Map, AUTO)




