/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TABLE_V1_TABLE_V1_TABLE_PB_H_INCLUDED
#define PB_TABLE_V1_TABLE_V1_TABLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _table_v1_ScalarType {
    table_v1_ScalarType_SCALAR_TYPE_UNSPECIFIED = 0,
    table_v1_ScalarType_SCALAR_TYPE_I8 = 1,
    table_v1_ScalarType_SCALAR_TYPE_U8 = 2,
    table_v1_ScalarType_SCALAR_TYPE_I16 = 3,
    table_v1_ScalarType_SCALAR_TYPE_U16 = 4,
    table_v1_ScalarType_SCALAR_TYPE_I32 = 5,
    table_v1_ScalarType_SCALAR_TYPE_U32 = 6,
    table_v1_ScalarType_SCALAR_TYPE_F32 = 7
} table_v1_ScalarType;

/* Struct definitions */
typedef struct _table_v1_ScalarArray {
    table_v1_ScalarType type;
    pb_callback_t signed_values;
    pb_callback_t unsigned_values;
    pb_callback_t float_values;
} table_v1_ScalarArray;

typedef struct _table_v1_Curve {
    bool has_x_axis;
    table_v1_ScalarArray x_axis;
    bool has_cells;
    table_v1_ScalarArray cells;
} table_v1_Curve;

typedef struct _table_v1_Map {
    bool has_x_axis;
    table_v1_ScalarArray x_axis;
    bool has_y_axis;
    table_v1_ScalarArray y_axis;
    bool has_cells;
    table_v1_ScalarArray cells;
} table_v1_Map;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _table_v1_ScalarType_MIN table_v1_ScalarType_SCALAR_TYPE_UNSPECIFIED
#define _table_v1_ScalarType_MAX table_v1_ScalarType_SCALAR_TYPE_F32
#define _table_v1_ScalarType_ARRAYSIZE ((table_v1_ScalarType)(table_v1_ScalarType_SCALAR_TYPE_F32+1))

#define table_v1_ScalarArray_type_ENUMTYPE table_v1_ScalarType




/* Initializer values for message structs */
#define table_v1_ScalarArray_init_default {_table_v1_ScalarType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define table_v1_Curve_init_default      {false, table_v1_ScalarArray_init_default, false, table_v1_ScalarArray_init_default}
#define table_v1_Map_init_default        {false, table_v1_ScalarArray_init_default, false, table_v1_ScalarArray_init_default, false, table_v1_ScalarArray_init_default}
#define table_v1_ScalarArray_init_zero   {_table_v1_ScalarType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define table_v1_Curve_init_zero         {false, table_v1_ScalarArray_init_zero, false, table_v1_ScalarArray_init_zero}
#define table_v1_Map_init_zero           {false, table_v1_ScalarArray_init_zero, false, table_v1_ScalarArray_init_zero, false, table_v1_ScalarArray_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define table_v1_ScalarArray_type_tag    1
#define table_v1_ScalarArray_signed_values_tag 2
#define table_v1_ScalarArray_unsigned_values_tag 3
#define table_v1_ScalarArray_float_values_tag 4
#define table_v1_Curve_x_axis_tag        1
#define table_v1_Curve_cells_tag         2
#define table_v1_Map_x_axis_tag          1
#define table_v1_Map_y_axis_tag          2
#define table_v1_Map_cells_tag           3

/* Struct field encoding specification for nanopb */
#define table_v1_ScalarArray_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, REPEATED, SINT32,   signed_values,     2) \
X(a, CALLBACK, REPEATED, UINT32,   unsigned_values,   3) \
X(a, CALLBACK, REPEATED, FLOAT,    float_values,      4)
#define table_v1_ScalarArray_CALLBACK pb_default_field_callback
#define table_v1_ScalarArray_DEFAULT NULL

#define table_v1_Curve_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  x_axis,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cells,             2)
#define table_v1_Curve_CALLBACK NULL
#define table_v1_Curve_DEFAULT NULL
#define table_v1_Curve_x_axis_MSGTYPE table_v1_ScalarArray
#define table_v1_Curve_cells_MSGTYPE table_v1_ScalarArray

#define table_v1_Map_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  x_axis,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  y_axis,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cells,             3)
#define table_v1_Map_CALLBACK NULL
#define table_v1_Map_DEFAULT NULL
#define table_v1_Map_x_axis_MSGTYPE table_v1_ScalarArray
#define table_v1_Map_y_axis_MSGTYPE table_v1_ScalarArray
#define table_v1_Map_cells_MSGTYPE table_v1_ScalarArray

extern const pb_msgdesc_t table_v1_ScalarArray_msg;
extern const pb_msgdesc_t table_v1_Curve_msg;
extern const pb_msgdesc_t table_v1_Map_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define table_v1_ScalarArray_fields &table_v1_ScalarArray_msg
#define table_v1_Curve_fields &table_v1_Curve_msg
#define table_v1_Map_fields &table_v1_Map_msg

/* Maximum encoded size of messages (where known) */
/* table_v1_ScalarArray_size depends on runtime parameters */
/* table_v1_Curve_size depends on runtime parameters */
/* table_v1_Map_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
