// SPDX-License-Identifier: MIT

use std::{env, fs, path::PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("generator is stored below the repository root")
        .to_path_buf();
    let generated_dir = root.join("build/rust-proto");
    let checked_in = root.join("rust/table/src/generated/table.v1.rs");
    fs::create_dir_all(&generated_dir).expect("generated output directory is available");

    let mut config = prost_build::Config::new();
    config.out_dir(&generated_dir);
    config.protoc_executable(
        protoc_bin_vendored::protoc_bin_path().expect("vendored protoc is available"),
    );
    config
        .compile_protos(
            &[root.join("proto/table/v1/table.proto")],
            &[root.join("proto")],
        )
        .expect("Table schema compiles with Prost");

    let generated = generated_dir.join("table.v1.rs");
    let content = format!(
        "// SPDX-License-Identifier: MIT\n// @generated by table-rust-proto; do not edit.\n\n{}",
        fs::read_to_string(generated).expect("Prost generated table.v1.rs")
    );
    if env::args().any(|argument| argument == "--check") {
        let current = fs::read_to_string(&checked_in)
            .unwrap_or_else(|_| panic!("{} is missing", checked_in.display()));
        assert_eq!(current, content, "checked-in Prost bindings are stale");
    } else {
        fs::create_dir_all(
            checked_in
                .parent()
                .expect("checked-in output has a parent directory"),
        )
        .expect("checked-in output directory is available");
        fs::write(&checked_in, content).expect("checked-in Prost bindings are writable");
        println!("Generated {}", checked_in.display());
    }
}
